config/routes.rb
Rails.application.routes.draw do
  root 'weather_forecasts#index'
  get '/forecast', to: 'weather_forecasts#forecast', as: 'forecast'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_forecasts_controller.rb
class WeatherForecastsController < ApplicationController
  before_action :set_address, only: :forecast

  def index
  end

  def forecast
    if @address
      begin
        @weather_forecast = Rails.cache.fetch(@address, expires_in: 30.minutes) do
          geocode = GeocodeService.call(@address)
          WeatherService.call(geocode.latitude, geocode.longitude)          
        end
      rescue => e
        flash.alert = e.message
      end
    end
  end

  private

  def set_address
    @address = params[:address]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_forecasts_helper.rb
module WeatherForecastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather_forecasts/forecast.html.erb
<% unless @weather_forecast %>
  <% flash.each do |type, message| %>
    <div class="flash data-turbo-temporary flash-<%= type %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

<% if @weather_forecast %>
  <div class="weather-forecast">
    <h2>Weather Forecast</h2>
    <div class="weather-info">
      <p><span>Current temperature:</span> <%= @weather_forecast.temperature %>°F</p>
      <p><span>Minimum temperature:</span> <%= @weather_forecast.temperature_min %>°F</p>
      <p><span>Maximum temperature:</span> <%= @weather_forecast.temperature_max %>°F</p>
      <p><span>Humidity:</span> <%= @weather_forecast.humidity %>%</p>
      <p><span>Pressure:</span> <%= @weather_forecast.pressure %> hPa</p>
      <p><span>Description:</span> <%= @weather_forecast.description %></p>
    </div>
  </div>
<% end %>

<%= link_to 'Search Again', root_path, class: 'nice-back-btn' %>

app/views/weather_forecasts/index.html.erb
<form action="<%= forecast_path %>" method="get" class="weather-form">
  <label for="address">Enter Address with Zip Code</label>
  <input type="text" id="address" name="address" class="input-field">
  <button type="submit" class="submit-button">Get Weather Forecast</button>
</form>